---
# vars file for roles/app

BACKEND_HOST: "{{ VAULT_BACKEND_HOST }}"
NETWORK_NAME: "{{ VAULT_NETWORK_NAME }}"

DATABASE_HOST: "{{ VAULT_DATABASE_HOST }}"
DATABASE_NAME: "{{ VAULT_DATABASE_NAME }}"
DATABASE_USER: "{{ VAULT_DATABASE_USER }}"
DATABASE_PASSWORD: "{{ VAULT_DATABASE_PASSWORD }}"
